// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------------- //
// dshot_bidir_300 //
// --------------- //

#define dshot_bidir_300_wrap_target 0
#define dshot_bidir_300_wrap 26

#define dshot_bidir_300_BIT_PERIOD 40

static const uint16_t dshot_bidir_300_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block                      
    0x6050, //  1: out    y, 16                      
    0x00e4, //  2: jmp    !osre, 4                   
    0x000c, //  3: jmp    12                         
    0x6041, //  4: out    y, 1                       
    0x0069, //  5: jmp    !y, 9                      
    0xfd01, //  6: set    pins, 1                [29]
    0xe500, //  7: set    pins, 0                [5] 
    0x0002, //  8: jmp    2                          
    0xee01, //  9: set    pins, 1                [14]
    0xf400, // 10: set    pins, 0                [20]
    0x0002, // 11: jmp    2                          
    0x0000, // 12: jmp    0                          
    0xe04a, // 13: set    y, 10                      
    0x1f8e, // 14: jmp    y--, 14                [31]
    0xf580, // 15: set    pindirs, 0             [21]
    0xe05f, // 16: set    y, 31                      
    0x4a01, // 17: in     pins, 1                [10]
    0x0091, // 18: jmp    y--, 17                    
    0x4801, // 19: in     pins, 1                [8] 
    0x8020, // 20: push   block                      
    0xe05f, // 21: set    y, 31                      
    0x4a01, // 22: in     pins, 1                [10]
    0x0096, // 23: jmp    y--, 22                    
    0x8020, // 24: push   block                      
    0xff81, // 25: set    pindirs, 1             [31]
    0xff01, // 26: set    pins, 1                [31]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program dshot_bidir_300_program = {
    .instructions = dshot_bidir_300_program_instructions,
    .length = 27,
    .origin = -1,
};

static inline pio_sm_config dshot_bidir_300_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + dshot_bidir_300_wrap_target, offset + dshot_bidir_300_wrap);
    return c;
}

static inline void dshot_bidir_300_program_init(PIO pio, uint sm, uint offset, uint pin) {
    pio_sm_config c = dshot_bidir_300_program_get_default_config(offset);
    sm_config_set_set_pins(&c, pin, 1);
    sm_config_set_in_pins(&c, pin);
    pio_gpio_init(pio, pin);
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, true);
    gpio_set_pulls(pin, true, false);  // up, down
    sm_config_set_out_shift(&c, false, false, 32);   // auto-pull enabled
    sm_config_set_in_shift(&c, false, false, 32);
    double clocks_per_us = clock_get_hz(clk_sys) / 1000000;
    // 3.333us per bit for dshot300
    sm_config_set_clkdiv(&c, 3.333 / dshot_bidir_300_BIT_PERIOD * clocks_per_us);
    pio_sm_init(pio, sm, offset, &c);
}

#endif

